openebs/jiva

.travis.yml
Previous Go Version: 1.7.1
New Go Version: 1.9.1
=> Updated Go to v1.9.1

frontend/gotgt/frontend.go, scripts/push, vendor.conf
=> Reconfigure jiva to to use the latest gotgt vendor changes

Dockerfile.dapper, app/replica.go, backend/file/file.go, backend/remote/remote.go, ci/start_init_test.sh, controller/control.go, controller/replicator.go, replica/client/client.go, replica/replica.go, replica/rest/model.go, replica/rest/replica.go, replica/rest/router.go, replica/server.go, sync/sync.go, types/types.go
Jiva clone feature  …
1. Now cloned volumes can be created from running volumes and can further be used in RO/RW mode.
2. Two new flags have been added to replica start-script for this feature:
--cloneIP : This is the service IP of the controller which exposes the volume to be cloned.
--snapName : Name of the  snapshot which needs to be cloned.
3. A new replica type "clone" has been added.
=> Jiva replica clone feature

sync/sync.go
=> Set rebuild only if clone snapshot present at source

rpc/server.go
=> Avoid creation of goroutines for each IO at replica

frontend/gotgt/frontend.go
=> Add nil check while stopping frontend

replica/rpc/server.go, replica/server.go, rpc/server.go
=> Create monitor channel before attempting to connect to controller

rpc/client.go
Controller does retrying IO to replica when IO gets timed out on replica. Response received from replica for IOs after timeout are not considered as success response. Also, controller doesn't take new IOs until response (either error/timeout/success) is received from all the replicas. This will timeout the client.
This PR is to make timeout retry count as 0, so that, retries won't happen on timed out IOs.
A routine will be waiting for an IO response from client, and also, when it times out, it prints the error message by taking the length from the message. At the same time, if error happens on that IO, another routine dedicated for client can modify the message. This leads to race between these two go routines.
This PR covers the race by not printing the length of the message. …
=> Remove retries, and fix a race condition in logging

ci/start_init_test.sh, controller/multi_writer_at.go, controller/rest/model.go, controller/rest/replica.go
Take locks in multiwriter error handling and prometheus https://github.com/openebs/jiva/issues/67
=> Take locks in multiwriter error handling and prometheus logging

ci/start_init_test.sh
=> Cleanup old containers while preparing for ci and print container logs in failure cases

scripts/push
=> Change tag for ci image to ci-0.5.5 for this branch

ci/start_init_test.sh, controller/control.go, controller/rest/model.go, controller/rest/volume.go, replica/server.go
Cherry-picked from https://github.com/openebs/jiva/commit/eae7fbb13d353f3bc7219409b199e86b88612641
=> Fixes for replica restarts

app/replica.go, controller/control.go, controller/replicator.go, rpc/wire.go
=> Fix race conditions in Read/Write calls

backend/remote/remote.go, ci/start_init_test.sh, controller/control.go, controller/rebuild.go, controller/replicator.go, controller/rest/replica.go, rpc/client.go, rpc/wire.go
This PR is to add logs in verifyrebuild / updatepeerdetails / "error reading from replica" code path of controller.
Also, have minor fixes for ci script.
Signed-off-by: Vishnu Itta <vitta@mayadata.io>
=> [TA1902] Logs in verifyrebuild

Dockerfile.dapper, package/Dockerfile
=> [TA1842] Change base image of Dockerfile to openebs/jiva:0.5.4

controller/control.go, controller/rest/replica.go, replica/rest/replica.go
This PR adds logs to REST API handling in controller.
=> Logs in REST API handling in controller

sync/sync.go
On branch US1680-fix-logs-on-sync-with-sc
modified:   sync/sync.go
-  To provide more descriptive error messages to the user.
-  Appended the errors also in the logs messages to know the cause of error.
-  None
-  Deploy the clone replica and you will be able to see more desriptive logs and
errors.
5. Any specific message for reviewer ?
-  No
=> [TA325, TA329] fix the error messages in clone/sync process

README.md
Signed-off-by: Rajat Varyani <rajat.varyani@outlook.com>
=> #59 Fix documentation broken links in README

.gitlab-ci.yml
refactor(yaml): Update the gitlab CI Yaml to add platforms and update baseline script.
=> refactor(yaml): Update the gitlab CI Yaml to add platforms and update baseline script.

controller/rebuild.go, frontend/tgt/scsi.go
This typo occurred twice in comments that makes the doc, so cleaning up.
Thanks
=> Fix typo: "happenes" is a misspelling of "happens"

Dockerfile.dapper, replica/client/client.go
=> Extracted common values and functions

app/replica.go, frontend/gotgt/frontend.go, frontend/rest/model.go
This removes unnecessary type declaration.
=> Running gofmt -s

README.md
=> Minor changes to doc

ci/start_init_test.sh
This functionality was removed earlier but missed to remove its test code.
=> fix(Snapshot): Remove unit test code for RO functionality

ci/start_init_test.sh
=> Remote iterative docker option in ci tests

backend/file/file.go, backend/remote/remote.go, controller/control.go, controller/multi_writer_at.go, controller/replicator.go, frontend/gotgt/frontend.go, frontend/rest/frontend.go, frontend/tcmu/frontend.go, frontend/tgt/frontend.go, replica/diff_disk.go, replica/replica.go, replica/server.go, rpc/client.go, rpc/server.go, rpc/types.go, types/types.go
=> Add support for Sync and Unmap

vendor.conf
=> Update to latest gotgt to support sync functionality from frontend

.gitlab-ci.yml
**What this PR does / why we need it**:
- Update the pipeline and baseline references to mdap ci.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
**Special notes for your reviewer**:
=> feat<CI>:Update gitlab yaml to work with mdap ci.

.gitlab-ci.yml
**What this PR does / why we need it**:
- Decrease the number of platform pipelines to 3 for master branch
- Platform for master branches will consist of AKS, EKS and GKE.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
**Special notes for your reviewer**:
=> Reduce the number of platform pipelines for master branches.

.gitlab-ci.yml
Signed-off-by: atulabhi <atulabhi@gmail.com>
=> updated trigger url in gilab yaml

rpc/server.go
- Issue Ref: openebs/openebs#1387
- Log and handle the case of disk-detach cases (input/output error)
in case it's `EIO` error fatal the replica.
Note:
- What happens to running replica ?
Replica will be fataled.
- What will happen upon replica restart after fatal?
Replica will always be fataled until disk is attached
- What will happen to controller ?
It will remove the fataled replica, and will continue to serve
IO's if quorum is met.
=> [TA4759] fix(replica): handle case of disk-detach

.gitlab-ci.yml, Makefile
Added build_gitlab in script in gitlab-ci.yml file.
=> fix(CI): Create new target for make to run with gitlab-ci.yml for 0.8.x branch. 

ci/start_init_test.sh, controller/rest/model.go, controller/rest/timeout.go, error-inject/default.go, error-inject/inject.go, rpc/client.go, rpc/server.go, rpc/wire.go
Following commits are taken for 0.8.1
-  [TA4284] fix(rpc): close connection at the client & server on errors or ping-timeout
-  [TA4759] fix(replica): handle case of disk-detach 
=> cherry-pick(jiva): pick the changes for 0.8.1

.gitlab-ci.yml, Makefile
Signed-off-by: sathyaseelan <sathyaseelan.n@cloudbyte.com>
- Modified gitlab integration yaml
- updated Makefile
=> refactor <CI>: Modified gitlab integration yaml

backend/remote/remote.go, ci/start_init_test.sh, controller/control.go, error-inject/default.go, error-inject/inject.go, replica/backup.go, replica/replica.go, replica/server.go, rpc/server.go, rpc/wire.go
Cherry pick following commit
- [TA4197] fix(replica): set timeout to nolimit for open req (#183)
=> cherry-pick(TA4197): pick commit for v0.8.x

vendor.conf
=> Update gotgt version

.golangci.yml
This commit add .golangci.yml to integrate golangci for checking
various go relates issues.
=> Feat(ci): add golang ci

README.md
Add badge and detailed license scan report from FOSSA
on the code and related dependencies.
=> chore(license): add fossa license scan badge

app/controller.go, app/replica.go, controller/rest/replica.go, replica/rest/replica.go
This commit removes the unnecessary logs generated for getting stats via rest calls.
=> feat(logs): remove logs from stats endpoint

.golangci.yml, app/controller.go, app/replica.go, backend/file/file.go, backend/remote/remote.go, ci/start_init_test.sh, controller/control.go, controller/rebuild.go, controller/replicator.go, controller/rest/replica.go, controller/rest/timeout.go, error-inject/default.go, error-inject/inject.go, replica/backup.go, replica/backup_test.go, replica/client/client.go, replica/diff_disk.go, replica/replica.go, replica/replica_test.go, replica/rest/model.go, replica/rest/replica.go, replica/rest/router.go, replica/revision_counter.go, replica/server.go, sync/sync.go, types/types.go
This commit rebase the v0.9.x with the master. Following PR's will be added
- feat(ci, lint): add golang ci (#199)
- fix(jiva): update revisioncounter during replica rw mode (#203)
- feat(logs): remove logs from stats endpoint (#205)
- feat(replica): optimize ssync to do only during required cases (#204)
- fix(replica): bad file descriptor error (#202)
=> Cherry pick v0.9.x

vendor.conf
=> update(gotgt): add latest commit hash in vendor.conf

vendor.conf
=> update(jiva): add latest gotgt commit hash in vendor.conf (#210)

.gitlab-ci.yml
- Enable e2e pipelines to run on openshift
=> feat(gitlab-ci): Add openshift platform to mdap ci for v1.0.x branch

package/Dockerfile
Upgrade to the latest to get the fixes for the known security vulnerabilities in Ubuntu. 
=> chore(build): update the base ubuntu to latest

app/snapshot.go, ci/start_init_test.sh, package/Dockerfile, replica/backup.go, replica/diff_disk.go, replica/replica.go, replica/replica_test.go, replica/server.go, scripts/package
Cherry-pick:
-  fix(ci): add restart policy for clone replica for testcases execution
-  fix(jiva): Introduce jivactl command for cli operations
-  fix(jiva): handle corner cases for snapshot delete
=> Cherry pick v1.0.0

app/replica.go, controller/control.go, replica/backup.go, replica/diff_disk.go, replica/replica.go, replica/replica_test.go, scripts/ci, types/types.go
This commit increase the maximumChainLength default value and also adds capability 
to configure it via environment variable.
=> Too many snapshots

app/replica.go, controller/control.go, replica/backup.go, replica/diff_disk.go, replica/replica.go, replica/replica_test.go, types/types.go
This commit fixes the issue by increasing the maxRemainSnapshot
=> fix(replica): too many snapshots created (#228)

ci/start_init_test.sh, replica/diff_disk.go, replica/replica.go
Fix: openebs/jiva#230
This commit fixes the issue of broken file system at the
application side.
This is happening due to the hardlinked files were pointing to the 
older fd's which is not valid anymore after the hardlinking of child
to parent snapshot, since it's still pointing to the older data.
So files need to be reopened and their reference should be updated
with the new one with the coalesced data.
=> fix(replica): fix broken fs due to delete snapshot

controller/control.go, controller/rest/volume.go
=> fix(snap delete): add missing unlock for error case

.gitlab-ci.yml
- Enable e2e pipelines to run on openshift
=> refactor(gitlab-ci): Add openshift platform to mdap ci for v1.1.x branch

frontend/gotgt/frontend.go
=> fix(gotgt): send unique uuid for generating serial no

alertlog/alertlog.go, app/add_replica.go, app/backup.go, app/replica.go, app/rm_replica.go, app/snapshot.go, controller/control.go, go.mod, go.sum
Signed-off-by: moteesh <moteesh@gmail.com>
=> Alertlogs for Jiva Replica operations create/delete/snapshot/clone

replica/client/client.go
Fixes https://github.com/openebs/openebs/issues/2775
Signed-off-by: Rounak Agarwal <rounakr.ag73@gmail.com>
=> Refactor 22 lines occurring 2 times in client.go

sync/agent/process.go
Greetings,
I've refactored 21 lines occurring 3 times in process.go. 
This is my first ever commit and PR about something in Go, and I must admit, I've never written a single line of a Go code before. If something is horribly wrong, then I'm so sorry.
Thanks
=> Refactored 21 lines occurring 3 times in process.go

.travis.yml
=> fix(travis): bump go version in travis

controller/control.go, replica/client/client.go, sync/sync.go
- Remove WO replica if new replica with greater revision count
get added to controller.
=> [WIP] fix(controller): remove wo replica

backend/remote/remote.go, ci/start_init_test.sh, controller/control.go, replica/replica.go, replica/rest/model.go, replica/rest/replica.go, replica/server.go
- This commit fixes an issue where replica was getting revision count
value as zero since complete changes were not checked in into the last
commit.
- Add ci to test the replica restart optimization
=> fix(replica): add replica with greater revision count

.gitlab-ci.yml
- Commented the curl request to trigger pipeline in packet for PR merges as we were triggering pipelines to schedule a time with ci tag.
=> refactor(gitlab-yaml): Removed the request to trigger pipeline in packet

app/controller.go, app/replica.go, ci/start_init_test.sh, replica/replica.go, rpc/client.go, types/types.go, util/util.go
=> fix(jiva): make read and write timeouts configurable (#272)

CHANGELOG.md
=> doc(changelog): add changelog for 1.7.0-RC1

.travis.yml, Makefile, ci/start_init_test.sh, scripts/ci, scripts/package, scripts/push
- auto build and push arm64 and amd64 binaries
- make tests dependent on the platform
- move push to after success
=> feat(build): enable auto build for arm64 binaries

app/controller.go, ci/start_init_test.sh, controller/control.go, controller/rebuild.go
- This commit comment out the autosnapshot deletion related code for now. This
will be enabled by making it configurable in the upcoming releases.
- Fixes: openebs/openebs#2956
=> revert(controller): comment out autosnapdeletion

app/controller.go, ci/start_init_test.sh, controller/control.go, controller/rebuild.go, sync/sync.go
revert(controller): disable autosnapshot deletion (#280)
revert(replica): comment revision count related checks at replica (#281)
=> cherry-pick(jiva): add latest changes to v1.6.x

app/controller.go, ci/start_init_test.sh, controller/control.go, controller/rebuild.go, sync/sync.go
revert(controller): disable autosnapshot deletion (#280)
revert(replica): comment revision count related checks at replica (#281)
=> cherry-pick(jiva): add latest changes to v1.7.x

app/controller.go, ci/start_init_test.sh, controller/control.go, controller/rebuild.go, sync/sync.go
revert(controller): disable autosnapshot deletion (#280)
revert(replica): comment revision count related checks at replica (#281)
=> cherry-pick(jiva): add latest changes to v1.8.x

backend/remote/remote.go
=> fix(replica): print http resp for bad status

CHANGELOG.md
=> doc(changelog): add info about latest improvements and bug fixes

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/pull_request_template.md, MAINTAINERS, RELEASE.md, code-standard.md, developer-setup.md
=> docs(project): add project specific docs

CHANGELOG.md
=> chore(docs): update changelog for 1.10.0 release

ci/feature_tests.sh, ci/suite.sh, replica/replica.go
=> fix(maxChainLen): maxChainLen to 1024, bug fix for MAX_CHAIN_LENGTH env

Makefile, scripts/push
Removing a few more hardcoded references to openebs, seeing during pushing jiva docker image. 
=> refactor(build): make the org configurables

Makefile, scripts/push
(cherry picked from commit 98c362442c90c727a0e319bfb21f5869d28cf521)
=> refactor(build): make the org configurables (#313)

Makefile, controller/control.go, replica/replica.go, sync/sync.go, tests/e2e/chaos.go, tests/e2e/container_start_stop.go, tests/e2e/ios.go, tests/e2e/replica.go, tests/e2e/snapshot.go, tests/functional/add_replica.go, tests/functional/config.go, tests/functional/controller.go, tests/functional/replica.go, tests/functional/test_checkpoint.go, tests/functional/test_functions.go
* Fix issue with deletion of user created snapshots
* update and improve functional tests
Signed-off-by: payes <payes.anand@mayadata.io>
=> cherry-pick(auto-delete-snapshot-fix): remove empty elements from DeleteCandidateChain

changelogs/released/v2.0.0-RC1/319-payes, changelogs/released/v2.0.0-RC1/321-payes, changelogs/released/v2.0.0-RC2/322-payes
Signed-off-by: payes <payes.anand@mayadata.io>
=> chore(docs): update changelog for v2.0.0 release

README.md
=> update(README): add HackMD badge

changelogs/released/v2.2.0-RC1/327-payes, changelogs/released/v2.2.0-RC1/328-payes
=> chore(docs): update changelog for v2.2.0 release

CHANGELOG.md
=> chore(docs): update CHANGELOG.md file

.github/workflows/build.yml, .github/workflows/release.yml, CHANGELOG.md, changelogs/released/v2.3.0-RC1/331-shubham14bajpai
This PR adds the changelog for v2.3.0 
- it also fixes the deprecated envs in github workflow
=> chore(CHANGELOG): add changelogs for v2.3.0

.github/workflows/build.yml, .github/workflows/release.yml
This PR fixes the tag info required while building the multi-arch images in github actions.
=> fix(actions): fix tag info in build & release workflows

changelogs/released/v2.4.0-RC1/334-prateekpandey14
=> chore(CHANGELOG): add changelogs for v2.4.0

.github/workflows/build.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml
This PR updates the buildx action version to the latest stable release.
=> chore(build): update the buildx action verison

changelogs/released/v2.6.0-RC1/343-payes, changelogs/released/v2.6.0-RC1/344-payes
=> chore(CHANGELOG): add changelogs for v2.6.0

.github/workflows/build.yml
=> fix(actions): fix the image tag for branches

CHANGELOG.md, changelogs/released/v2.11.0-RC1/353-shubham14bajpai, changelogs/unreleased/347-shubham14bajpai
This PR updates changelog for v2.11.0
=> chore(CHANGELOG): add changelogs for v2.11.0
