openebs/jiva

.travis.yml, Makefile, ci/start_init_test.sh
* Create the vsm on docker-net
* Make the paths relative, helps with forked branches build
* Install iscsiadm for ci
* run the vdbench basic tests
* Run the vdbench tests in foreground
=> Enable CI for jiva with vdbench tests (#1)

Dockerfile.dapper, controller/rest/router.go, replica/rest/router.go
**What this PR does / why we need it**:
* This PR refers issue #16 and [#380](https://github.com/openebs/openebs/issues/380)
* Adds endpoint `/metrics` in controller and replica
* Adds dependency of prometheus in Dockerfile
**How this commit address the issue**:
* Prometheus now collects basic metrics from controller and replica.
**How to verify this change**
* Build new image and binary and then run it locally by `./longhorn --url "http://localhost:9501" controller vol`
* or Run it in Docker container
**Note:**
* Custom metrics not added yet, will be added later an issue #16 is
created for this
* You need to build a new binary in order to see the metrics in openebs
setup
=>  Add endpoint "/metrics" in Controller and replica

package/Dockerfile
optimize docker image, reference openebs/openebs#553
=> make docker image smaller

controller/control.go, controller/rest/model.go, controller/rest/replica.go, controller/rest/volume.go
1. Why is this change necessary ?
- To expose size at `/v1/stats` endpoint
- To monitor `/v1/register`
2. How does this change address the issue ?
- Adds a method bind with controller to get size
- Adds prometheus counter variables that is used to count the
no of registration so far.
3. How to verify this change ?
- Run `curl controllerIP:Port/v1/stats` while running controller
locally or with openebs-operator.
4. What side effects does this change have ?
- none
5. Other details
- fix: [#858](https://github.com/openebs/openebs/issues/858)
fix: [#266](https://github.com/openebs/openebs/issues/266)
=> Add varibales to count volume registration in prometheus

controller/rest/model.go, controller/rest/volume.go
This commit adds uptime and volume name fields in volumestats struct.
fix: openebs/openebs#886
corresponding changes in maya done PR[#184](https://github.com/openebs/maya/pull/184)
=> Add uptime and volume name in stats struct

app/replica.go
Most of the kubernetes examples advocate specifying the capacity with "i" like Gi or GiB. The current units -- vendored package doesn't handle it. 
This PR provides and interm fix that will avoid sending openebs volume into errored state during creation. A cleaner fix needs to be implemented to handle different capacity input parameters (See https://github.com/openebs/openebs/issues/541)
=> Interm fix for handling size formats with i

frontend/gotgt/frontend.go, scripts/push, vendor.conf
ci image is not tied to release tag anymore. 
probably can remove the repo -- jiva-ci eventually once all the scripts move to using jiva:ci
=> update ci image on every build

ci/start_init_test.sh
Fixes #37 
- Run vdbench test *only* when iSCSI device node is created
- Included pass/failure conditions to workload (vdbench) test
- Convert dd test to into simple DI test (md5sum)
- Include libiscsi iSCSI compliance suite with pass/failure conditions
=> Include Data-Integrity and iSCSI compliance test in Jiva-CI travis build 

ci/start_init_test.sh
This will avoid the use of same iSCSI volume by two initiators.
=> Remove iSCSI session from node before starting libiscsi test suite

Dockerfile.dapper, app/replica.go, backend/file/file.go, backend/remote/remote.go, ci/start_init_test.sh, controller/control.go, controller/replicator.go, replica/client/client.go, replica/replica.go, replica/rest/model.go, replica/rest/replica.go, replica/rest/router.go, replica/server.go, sync/sync.go, types/types.go
Enhance jiva for clone feature  …
1. This PR will add sync and rebuild capabilities in jiva as clone feature.
2. Now clone volume can be created from the running replicas volume and can be further used as RO/RW mode.
3. There is 3 new flags has been added, which has to passed while starting a clone replica with a new jiva-controller, to be clone to a particular snapshot.
- `cloneIP` : This is frontendIP of running controller, which will be used to make a clone request will be passed as a argument while starting clone replica.
- `clone`: Type of replica, now we can pass type as `clone` to trigger the clone API of jiva, which says the new replica is getting added as clone not as usual replica.
- `snapName` : Name of the  snapshot which will be synced to a new volume.
=> Jiva replica clone feature

ci/start_init_test.sh, controller/control.go, controller/rest/model.go, controller/rest/volume.go, replica/server.go
This pull request fixes the following issue:
The controller was not getting converted back to read-write mode when the replica came back up in case of single replica. The controller had to be restarted as a work around.
=> Fixes for replica failures

rpc/client.go
=> Fix typo on rpc client.go

controller/control.go
This will avoid the iscsi disk at client side to go in read only mode even when IOs are not being served.
This can hold the the app only for small amount of time based on the app.
=> Delay error response by 1 second when volume is in read only state

app/replica.go, controller/control.go, controller/multi_writer_at.go
This PR adds enhanced logging in the following scenarios:
1) When a replica registers at the controller
2) When a replica goes down because of the exit of one of its critical goroutines.
3) When the state of the volume is switched between R/W and R/O
=> Improve logging to detect replica failures

rpc/client.go, rpc/server.go, rpc/types.go, rpc/wire.go
We don't need data buffer for read request or write response, because they're
empty. For this purpose, we introduced `Size` in message struct. It will be the
intended size of read or write.
This PR has been picked from upstream.
https://github.com/rancher/longhorn-engine/commit/feb9f4b63e22702318a1bedd0912939fa9661e4a
=> rpc: Eliminate empty data transfer between client/server

replica/server.go
This will avoid a deadlock, if the connection establishment process breaks in between, and the controller sends a close for the replica. It will be a deadlock since there will be no listener for the channel until the connection process is complete, and the connection will not complete until it gets this lock.
=> Remove lock before signaling replica close

controller/control.go, replica/server.go
Adding logs at the suspecting places where we are changing the volume state from read/write state.
Also removing writing to the MonitorChannel which ends up closing the monitoring channel and triggers the registration to the controller, suspecting it might be causing/triggering registering code path which might be causing the controller panic.
=> Add logs when volume changes mode and remove signaling monitorChan

ci/start_init_test.sh, controller/control.go, controller/rebuild.go
This PR is to have ReplicationFactor (RF - configuration parameter for number of replicas). This is used to decide the number of replicas (replicaCount) that should be added to controller to mark volume as RW. Added logs to print the registration details.
API related to verifying rebuild status seems to be updating the replicaCount which is actually not required. Added logs for the same.
RF is currently initialized to 3, which eventually should come to longhorn controller binary from control plane. So, single replica testcases has been stopped in this PR, which should be enabled back once the configuration is received from control plane.
=> Using replication factor from global variable

controller/control.go
When the controller comes up the status of the volume should be read only.
The default for boolean variables in golang is false, so we need to set it explicitly.
=> Initialize volume mode as read only when controller starts

controller/control.go
There was a problem while clearing replica details from controller when replica goes down.
The address passed in RemoveReplica function contains the strings "tcp://" and ":9502".
But the registered replica list contains only ip addresses and we were checking for this ip substring in the passed address which is tcp://<ip str>:<port>.
So in case of two replica having IPs 10.10.10.10 and 10.10.10.1, the substring comparison of 10.10.10.1 will also be true for the replica with address tcp://10.10.10.10:9502 and we will remove wrong (or both) the replica in this case.
=> Rectify string comparision while removing replica from registered list and add logs

controller/control.go
Currently there can be only one replica in WO mode, we don't
allow any other replica to connect. So, if the last
replica remaining is in WO, we should disconnect it
so that other can connect and proceed.
=> remove the last replica if it is in WO mode.

ci/start_init_test.sh, controller/control.go
This PR is to simulate the case where the last replica that is connected to controller is in WO mode.
In this scenario, replica (which is in WO mode) closes itself when sync fails and re-registers with controller.
New code in `RemoveReplicaNoLock` that is handling this case specially is not required. This PR reverts that code.
Few other changes to 'ci' test:
- Increased the wait time to 200 seconds or 250 seconds in reaching the 'pass' state
- Collecting stack traces, replicas/volumes information during failure case
- Taking the head of the docker image during docker creation
=> [TA1772] Testcase for last replica being in WO mode

app/add_replica.go, app/controller.go, app/replica.go, ci/start_init_test.sh, controller/client/controller_client.go, controller/control.go, controller/rebuild.go, controller/replicator.go, replica/peer_details.go, replica/replica.go, replica/revision_counter.go, sync/sync.go
If replication factor is received from control plane, data corruption can be avoided.
Scenario:
2 Replicas are present.
1) Replica_1 is connected to controller and IOs have been started, but replica 2 did not connect till now.
2) Controller restarts and replica 2 connects before replica 1. Revision counter and peerCount at Replica_2 are 0, so controller thinks that it is a new deployment and starts the IOs on this replica.
3) Replica_1 now connects back to controller and its data is synced, assuming Replica_1 as source.
Now the data which was written earlier at Replica_1 is lost.  
Other fixes:
- There is unnecessary creation of TempServer and TempReplica during repeated registration. Removed the unnecessary creation.
=> Fetch Replication factor from env and make volume R/W only when >50% replicas are in R/W mode

scripts/push
There is need to create tagged images from non-master branches.
This PR is to revert PR#74 which limits the creation of tagged images to master branch.
However, creating images with latest tag need to be looked in holistic way when there are images built from multiple branches.
Signed-off-by: Vishnu Itta vitta@mayadata.io
=> Creating tagged images from non-master branch

app/replica.go, ci/start_init_test.sh, controller/control.go, rpc/client.go
In jiva, replica logs are not having timestamp details. This PR addresses it by adding a formatter to logrus to print timestamp in replica logs
When replica disconnects with controller, there are goroutines which doesn't get freed. This PR address by checking for error and returns to fix goroutines leak.
Added test cases for verifying quorum, and to goroutines leak fix
Also, reduced few iterations in ci script to reduce build time
Signed-off-by: Vishnu Itta <vitta@mayadata.io>
=> Timestamp in replica logs, goroutines leak fix

app/add_replica.go, controller/rebuild.go, sync/sync.go
This PR addresses the situation when the sync process breaks in between.
Logs seen after this issue is hit are as follows:
```
ERRO[0m[2018-07-13T06:55:17Z] Error adding replica, err: Bad response: 500 500 Internal Server Error: {"actions":{},"code":"Server Error","detail":"","links":{"self":"http://172.18.0.5:9502/v1/replicas/1"},"message":"Failed to find metadata for volume-snap-aec261ba-1f93-4b49-b671-257dac8f2789.img","status":500,"type":"error"}, will retry 
172.18.0.2 - - [13/Jul/2018:06:55:17 +0000] "POST /v1/replicas/1?action=close HTTP/1.1" 404 0
INFO[0m[2018-07-13T06:55:19Z] Closing replica                              
INFO[0m[2018-07-13T06:55:19Z] Close replica failed, s.r not set            
INFO[0m[2018-07-13T06:55:19Z] Addreplica tcp://172.18.0.5:9502 …
```
=> Reverse the current order of sync to avoid corrupting the snapshot chain

Dockerfile.dapper, package/Dockerfile
Related to #89
jiva:base is derived by stripping the content from the jiva:0.5.4, which created additional layers. 
```
docker image inspect openebs/jiva:base
"Layers": [
"sha256:c8aa3ff3c3d351787cc5f84d960870fad16c9615aab7aa47ab343906fc8cfc24",
"sha256:82718dbf791d95622b5edeedbfbc6d0f01d406d4035a30a416d51d2c7e193486",
"sha256:3a0404adc8bdbcf7cfc28ca3a3e703d6db86f4e11853664085f00add69ccb3d7",
"sha256:cd7b4cc1c2dd51a75939212a7b5c278eb899ac4330b9482038f72f7e6feba975",
"sha256:bf3d982208f5bad81239ff690e81ad90e28c3cd81634b079cb938757d2435902",
"sha256:0660c6278c9758a333dcc7267d2eac07ef2fdcf98a88b287fb2ee29e64d05b3d",
"sha256:992b95a03a4fae2d37a1349f66b39dddcb575c02db1b640b0bd61214f5623901", …
```
=> [TA1842] Set a fixed ubuntu image as base image

Dockerfile.dapper
This PR reverts the docker version update in https://github.com/openebs/jiva/commit/30883ee513559c57f0624b08940596b18a34e987
Go version has also been updated to get the following fix: https://github.com/golang/go/commit/a158382b1c9c0b95a7d41865a405736be6bc585f
=> Update versions for docker and go

app/controller.go, app/replica.go
On branch fix-controller-logs
modified:   app/controller.go
modified:   app/replica.go
-  We were not getting the details such as controllerIP, clusterIP in the
startController logs
-  We were not getting the details such as replicaType, dir, size, address
sync address etc in startReplica etc.
-  This commit add these logs.
-  None
=> [TA2052] Add details of replicaStart and controllerStart in logs

rpc/types.go
This PR was required because of the recent changes in the structure of data packets exchanged between controller and replica https://github.com/openebs/jiva/commit/24f78f39f9d35dce81a6e916ad0f6d8f7e0b9349.
It will resolve the issues arising because of the time gap between the upgrade of controller and replicas.
=> Update jiva version

app/replica.go
On branch fix-clone-logs
modified:   ../../../app/replica.go
-  Error was ignored while setting the status of cloned replcas.
-  Added the logs and err var to catch those errors.
-  None
=> [TA328] add error logs if clone is not completed.

controller/control.go, controller/rest/replica.go, replica/rest/replica.go
REST API code in controller uses controller related data structures with out any lock protection.
This causes Go routine crash as below trace:
```
2018/07/25 12:20:33 http: panic serving 172.18.0.4:49932: Passed type is not a struct got: invalid
goroutine 173 [running]:
net/http.(*conn).serve.func1(0xc4200a9680)
/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0xa886c0, 0xc420415740)
/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/openebs/jiva/vendor/github.com/rancher/go-rancher/api.getEmbedded(0xa69b00, 0x0, 0xbfda00, 0xb48c00, 0x9, 0x4112d9)
/go/src/github.com/openebs/jiva/vendor/github.com/rancher/go-rancher/api/api.go:30 +0x4bc
github.com/openebs/jiva/vendor/github.com/rancher/go-rancher/api.getCollection(0xa69b00, 0x0, 0x2) …
```
=> lock protection in API code of controller

controller/control.go, controller/rest/replica.go, replica/rest/replica.go, replica/server.go
In replicas of jiva volumes, during REST API handling, replica related data structures are used without any lock protection.
This leads to data race between reader and writer of those structures.
This PR is to lock protect of those structures during REST API handling.
This PR also adds logs to track REST APIs and its errors.
=> Lock protection for replica data structures during REST API handling

app/sync_agent.go, ci/start_init_test.sh, controller/client/controller_client.go, replica/client/client.go, replica/replica.go, replica/rest/model.go, replica/rest/replica.go, replica/server.go, rpc/server.go, sync/agent/process.go, sync/sync.go
This PR addresses the below issues when there are any breakages during sync process:
==> A port map has been maintained in sync-agent. This is supposed to be only for ssync servers that are created in that replica. But, it is getting updated even for ssync clients created in that replica. This can cause problem as below:
Consider ssync server is created on port 9759, and, this updated the port map. Due to reason that ssync client is crashed, that ssync server process still stays, and so, listener also exists.
During this time, if another replica have listener on 9759 and asked this replica to help in rebuilding, current code adds entry related to 9759 port to map, and deletes the entry from map once the file is synced.
Later, this port 9759 again can get alloted and cause 'bind port …
=> [TA2117][TA2118] Issues in sync process due to breakages

ci/start_init_test.sh, replica/rpc/server.go, rpc/server.go
On branch US2634-fix-goroutine-leaks
modified:   replica/rest/router.go
modified:   replica/rpc/server.go
modified:   replica/server.go
-  To fix the goroutine leaks in jiva.
-  Added an additional check before handling client requests for verification
of the expected rpc client from controller.
-  Added an additional field `ClientAddr` in the `replica.Server` which can be
used for verifying the clients and hence avoid goroutine leak.
-  None
-  Make request to replica by `curl replicaIP:9503` and open the debug/pprof UI
and you should not see the increase in the goroutines.
5. Any specific message for reviewer ?
-  None …
=> [TA2437] Fix goroutine leaks in jiva

ci/start_init_test.sh, controller/rest/delete.go, controller/rest/model.go, controller/rest/router.go, replica/client/client.go, replica/replica.go, replica/rest/delete.go, replica/rest/model.go, replica/rest/router.go, replica/server.go, util/util.go
On branch US2635-volume-deletion
modified:   controller/rest/model.go
modified:   controller/rest/router.go
modified:   controller/rest/volume.go
modified:   replica/client/client.go
modified:   replica/replica.go
-  Delete api from controller is not there in the controller.
-  Delete api does not delete all the contents of the directory.
-  Added an api `v1/delete` with method `DELETE` in replica to make delete request to all
the replicas to delete all the contents under mounted directory.(e.g,
`/var/openebs`)
-  Added an api `v1/delete` with method `POST` in controller to make delete request to all
the replicas to delete all the contents.
-  Made changes in …
=> [TA2491, TA2515] Purge replica files when replicas are deleted

ci/start_init_test.sh, replica/replica.go
On branch US2662-verify-file-extents-mapping
modified:   replica/replica.go
-  To verify whether the underlying filesystem supports extents mapping.
-  In the earlier code we were ignoring the error which verifies if the
filesystem supports extents mapping. So now we will catch the error
and error out the replica.
-  None.
-  ci is already added to verify the changes.
5. Any specific message for reviewer ?
-  No
=> [US2662] check if underlying filesystem supports extents mapping.

backend/remote/remote.go, ci/start_init_test.sh, controller/rest/model.go, controller/rest/router.go, controller/rest/timeout.go, error-inject/default.go, error-inject/inject.go
On branch fix-timeout-issue-while-registration
modified:   backend/remote/remote.go
modified:   controller/rest/model.go
modified:   controller/rest/router.go
new file:   controller/rest/timeout.go
modified:   error-inject/default.go
modified:   error-inject/inject.go
-  To fix the bug related to timeout issues
while registration of replica.
-  Added an endpoint `timeout` in controller to set the timeout
of registration at the run time.
-  None
-  Run ci, it should work fine.
=> [TA2653] Fix the travis timeout issue while registration

Dockerfile.dapper
jiva image is build by creating a build container that
downloads dependencies from external repositories. One
such dependency is on qcow tools project:
https://github.com/libyal/libqcow/
The older source tar has been removed from the above repo
which is causing jiva builds to fail. This PR updates
the build container to download from a recent active link.
Note: A more permanent solution is required to fix this flaky
builds due to breaking external dependencies. this will be taken 
up in the upcoming releases. 
=> fix(build): download qcow src from an active link

ci/start_init_test.sh, replica/extents.go, replica/replica.go, replica/server.go
On branch US3116-extent-mapping-bug
modified:   replica/replica.go
modified:   replica/server.go
This commit fixes the bug which was not fataling the replicas
if they are restarted due to unsupported underlying file system
where replicas store the data.
Add ci to verify the fix.
=> [TA2880, TA2881] fix(jiva): extents mapping bug

ci/start_init_test.sh, controller/control.go, controller/rest/model.go, controller/rest/volume.go
On branch US3005-verify-snapshot-name
modified:   controller/control.go
-  To fix the problem when snapshot with the given name already
exist.
-  verify if snapshot already exist in the chain list and then
proceed to create snapshot if snapshot with the given name
does not exist.
-  None
-  Add ci for the same, it should run fine.
5. Any specific msg for the reviewer?
-  Refer to US3005
-  Snapshots are created in the linear order, need to optimize it in better way.
=> [TA2643, TA2644] fix(snapshot): verify if snapshot already exist

ci/start_init_test.sh, controller/control.go, controller/rest/replica.go, sync/sync.go
On branch 3006-fix-add-replica
modified:   controller/control.go
modified:   controller/rest/replica.go
This commit fix the issue where the new replicas are getting added
even if the RF condition is met. i.e, (Replication Factor = Replica
count)
=> [TA3086] fix(replica): don't add replica if RF is met

backend/remote/remote.go, ci/start_init_test.sh, rpc/client.go
- modified: backend/remote/remote.go
- modified: rpc/client.go 
- modified: ci/start_init_test.sh
Issue:
There is a monitorping goroutine, which keeps on pinging the replicas every 2 seconds on the data path. This goroutine runs in parallel to the read/write IOs.
If the ping fails, it removes the replica entry from the controller. Ping has a timeout of 20 sec. 
Whenever the conn btw ctrl/rep breaks, the rpc client read call errors out closing reader/writer goroutines and setting error on that rpc client.
There is a time gap between closing reader/writer goroutine and closing the ping goroutine. In this time gap, if one more ping has been triggered, it will timeout eventually. But when it times out, it will again try to remove the replica from controller's list. If …
=> [US3310] fix(controller): Resolve issues with asynchronous ping goroutine

Makefile, scripts/push
Update the push script to use a similar convention like
other repos to have the following:
- master branch ci image will be tagged as "ci"
- non-master branch ci images will be tagged as "branch-name-ci"
The commit tagged (dev-commit) images pushed to openebs/jiva-ci
are also prefixed with the branch name. And will include the
release tag information. The new format will look like:
<branchname->0.7.0-<commit-id>
=> refactor(build): prefix ci images with branch name

ci/start_init_test.sh, replica/replica.go
Location table contains a mapping of the block number of the volume to the snapshot file containing its latest copy.
After resizing the volume at replica, we were not increasing the size of the location table.
When a read/write was being received for that block, we were trying to access the same location in the table which was causing the crash.
=> [US3272] fix(resize): Fix replica crash due to resize

Makefile, scripts/push
Update the push script to use a similar convention like
other repos to have the following:
- master branch ci image will be tagged as "ci"
- non-master branch ci images will be tagged as "branch-name-ci"
The commit tagged (dev-commit) images pushed to openebs/jiva-ci
are also prefixed with the branch name. And will include the
release tag information. The new format will look like:
<branchname->0.7.0-<commit-id>
(cherry picked from commit 6f6d9992567b5cb0801c6b49a4e88c8372d8748a)
=> refactor(build): prefix ci images with branch name (#122)

README.md
Though http link will automatically redirect to https but, still to maintain consistency and standardization suggesting for https.
Signed-off-by: ashish <ashish.knit.cs@gmail.com>
=> Changed Slack link from http to https

.gitlab-ci.yml
This PR contains the gitlab-ci yaml to build jiva and push the image with "commit id" to docker hub on each commit to 'Master' branch and run our E2E pipeline with new image.
Build Pipeline:
Signed-off-by: atulabhi <atulabhi@gmail.com>
=> added gitlab-ci yml to run ci and e2e in gitlab

Dockerfile.dapper
This commit fixes the issue which was happening due to
the changes in the golint project. Replacing the go get
path to golang.org/x/lint/golint
(cherry picked from commit 36e5c68bfdce43dcbe7d34b0450625cf46181064)
=> Fix golint issue while triggering build in travis

.gitlab-ci.yml, scripts/push
Commit based images are required to run OpenEBS-E2E . These images will be push by gitlab-runner based on the commit from the github. The commit is fetch from github and update as an environment variable (COMMIT ) in gitlab-runner which is being utilised in the push script.
=> updated gitlab-ci yml and push script to build and push commit based

app/replica.go, ci/start_init_test.sh, replica/backup.go, replica/client/client.go, replica/diff_disk.go, replica/replica.go, replica/rest/model.go, replica/rest/replica.go, replica/rest/router.go, replica/server.go, sync/sync.go
Why this feature was implemented ?
This feature was implemented to make sure we don't fallocate(create holes) on a file when it is helping in rebuilding of other replicas.
Why is it being removed now ?
Even if this data is synced and fallocate is called after that, the preload function in the replica being rebuilt takes care of removing this data over there.
=> Remove RO functionality for snapshots while syncing

controller/rest/model.go
This is part of the fix for openebs/openebs/issues/2214.
=> Fix a small typo in json tag of VolumeStats struct

Dockerfile.dapper
This commit upgrades the docker version used to build the env
to latest stable ones.
=> [TA3796] fix(travis): update Dockerfile.dapper

controller/rest/model.go, controller/rest/volume.go
JSON can only handle the data up to 53 bits precision,
so this needs to be converted into string.
=> [TA3763] fix(stats): change type of uptime to string

Dockerfile.dapper, ci/start_init_test.sh, controller/rest/model.go, controller/rest/timeout.go, error-inject/default.go, error-inject/inject.go, rpc/client.go, rpc/server.go, rpc/wire.go
Controller initiates a new connection upon replica registration,
this might create some problem due to concurrent goroutines, as some
of the goroutine may not have been exited. To ensure graceful close
of the connection, i have added CloseRead and CloseWrite in both 
replica and controller.
=> [TA4284] fix(rpc): close connection at the client side

.gitlab-ci.yml
- The push scripts of Jiva already use the $REPO variables, which gets
overwritten by gitlabs $REPO value causing the build to fail.
- Renamed the $REPO variable in gitlab to $BASELINE_REPO in gitlab.
=> fix(CI): Change the reference from $REPO to $BASELINE_REPO.

backend/remote/remote.go, ci/start_init_test.sh, controller/control.go, error-inject/default.go, error-inject/inject.go, replica/backup.go, replica/replica.go, replica/server.go, rpc/server.go, rpc/wire.go
Recently we have seen that if volume size is large then preload
takes time and hence openReplica fails due to timeouts and hence
neither of them succedes.
To resolve this issue, we have set timeout to zero, which means
there will be no timeout only for open requests.
fixes issue:  openebs/openebs#2311
=> [TA4197] fix(replica): remove timeout for open req

rpc/server.go
* fix(replica): add logs for io timeout in replica
Recently we have observed that controller was logging an error
if io timeout happened but in replica there was no sign of such
error. So log has been added to replica also which compare the
the time took for the request to complete with the operation timeout
and print logs if required.
Closes issue:  openebs/openebs#2398
=> cherrypick(replica): add logs for io timeout in replica (#186)

.gitlab-ci.yml
- Check for master and .x branches for build to trigger by using only:
refs option.
- Use the new CI_COMMIT_SHORT_SHA env to get the short commit SHA.
- Push the commit details to respective branches on e2e-infrastructure.
- Pass the branch details of JIVA to the platform repos to checkout e2e-infrastructure for that particular branch when the infra-setup stage is run.
- Deprecate GKE, EKS and AKS platforms.
- Run Packet platform, with k8s 1.11, 1.12 and 1.13 for master branch.
=> Enhancements and changes to GitLab CI YAML.

.gitlab-ci.yml
- Implement the fix for regex to work with GitLab.
- GitLab needs a '/' in the front and back of the regex.
=> Implement the fix for regex to work with GitLab.

ci/start_init_test.sh, rpc/client.go
Increase ping timeout to 40s since sync and unmap timeout is
30s, hence ping timeout should be greater than these.
=> fix(ping timeout): increase ping timeout

.gitlab-ci.yml
- The number of characters for the tag to be saved into the baseline is
being reduced from 8 to 7.
- By default the push script seems to be pushing tag with 7 characters
of the commit only.
=> refactor(gitlab-ci):update the tag to be pushed into the baseline

ci/start_init_test.sh, rpc/client.go
* fix(ping timeout): increase ping timeout
Increase ping timeout to 40s since sync and unmap timeout is
30s, hence ping timeout should be greater than these.
=> fix(cherrypick): Increase ping timeout  to 0.8.x

controller/control.go
Fixes: openebs/openebs#2482
- Replica is not able to register again if signalled to start already
but startSignal() failed. This is due to missing flag StartSignalled
which was set to true.
=> fix(controller): add missing flag StartSignalled in case of error

controller/control.go, vendor.conf
This PR cherry picks the following jiva stability fixes into 0.8.2:
- https://github.com/openebs/jiva/pull/195
- https://github.com/openebs/jiva/pull/197
=> chore(cherry-pick): jiva stability fixes from master to 0.8.2

backend/file/file.go, backend/remote/remote.go, ci/start_init_test.sh, controller/control.go, controller/rebuild.go, controller/replicator.go, error-inject/default.go, error-inject/inject.go, replica/backup_test.go, replica/replica.go, replica/replica_test.go, replica/rest/model.go, replica/rest/replica.go, replica/rest/router.go, replica/revision_counter.go, replica/server.go, sync/sync.go, types/types.go
Currently, jiva controller resets revisionCounter of replica to 0 whenever replica is added in WO mode. Jiva replica increments revisionCounter all the time.
When there is any disconnection or restarts of replica after revisionCounter is set to 0, then, it loses the context of the amount of data that replica had. This makes controller in picking wrong replica as the master.
This PR does the following:
- Remove re-setting revisionCounter to 0
- Controller sets replicaMode of replica to RW when it add replica in RW
- Controller sets replicaMode of replica to WO when it adds replica in WO mode
- Controller sets replicaMode of replica to RW when replica completed its sync process
- Increment revisionCounter in replica only when the replica is in RW state
Signed-off-by: Vitta …
=> fix(jiva): update revisioncounter only during rw mode

ci/start_init_test.sh, replica/client/client.go, sync/sync.go
This commit optimize the resync by checking the revision count. If the revision count of both the replicas
are same and the chain of both healthy and restarted replica is same, it wouldn't go for sync, rather it would be directly added RW replica after verifying the rebuild.
=> feat(replica): optimize resync

app/replica.go, ci/start_init_test.sh, controller/control.go, controller/rest/timeout.go, error-inject/default.go, error-inject/inject.go, replica/backup.go, replica/diff_disk.go, replica/rest/replica.go, replica/server.go, sync/sync.go, types/types.go
Recently it has been observed that replicas were crashing due to
frequent controller restart. This is happening due to the files
are getting closed just after the disconnection but it is trying to
punch holes on the closed files. So it was giving `bad file descriptor
error`.
This PR fix the above issue by closing the files gracefully after
draining the queued data in the HoleCreatorChan. Punch holes will
be done only in following case:
- If replica is master replica (which get start signal)
- If replica is reloaded
- If replica is in RW mode (i.e, Rebuilding is false)
Additionally it fixes some go vet errors also.
Fixes: openebs/openebs#2532
=> fix(replica): bad file descriptor error

GOVERNANCE.md, MAINTAINERS, NOTICE.md
This PR adds the current maintainer and reviewer list
for the openebs/maya project. Also links to the Governance
process outlined for the overall openebs projects in openebs/openebs#2547
=> docs(contributor): add governance and maintainers files

controller/control.go
This commit fix the issue openebs/openebs#2600, where replicas, were
not getting attached to controller after upgrade due to a missing
corner case in startReplica, where c.StartSignalled is not getting
updated to false in case of any error while adding the replicas.
=> fix(controller): set c.StartSignalled to false in case of error

app/add_replica.go, app/replica.go, ci/start_init_test.sh, replica/rest/replica.go, replica/rpc/server.go, replica/server.go, rpc/server.go, rpc/wire.go, sync/sync.go
This commit fixes the issue, where replica is getting blocked on
MonitorChan for forever while registration/sync process if controller
is restarted or removed the replicas due to network disconnection
or any other explicit reason.
Now replicas will be fataled as soon as controller is disconnected
after closing the files gracefully.
Upgrade scenarios have been changed also, now user should first upgrade
the controller, which will stop the replicas and then upgrade the
replicas one by one.
=> fix(replica): remove MonitorChan and improve autoregistration logic

app/add_replica.go, app/replica.go, ci/start_init_test.sh, package/Dockerfile, replica/rest/replica.go, replica/rpc/server.go, replica/server.go, rpc/server.go, rpc/wire.go, sync/sync.go
Cherry-pick:
- fix(replica): remove MonitorChan and improve autoregistration logic
-  chore(build): update the base ubuntu to latest
This commit fixes the issue, where replica is getting blocked on
MonitorChan for forever while registration/sync process if controller
is restarted or removed the replicas due to network disconnection
or any other explicit reason.
Now replicas will be fataled as soon as controller is disconnected
after closing the files gracefully.
Added a new function ReadMessage to read the reqeust's MagicVersion
to reject the request from invalid clients (exp: Prometheus) on data
connection, which by default scrapes from all the open ports.
Upgrade scenarios have been changed also, now user should first upgrade
the controller, which will stop the replicas and then upgrade …
=> cherry-pick(replica): remove MonitorChan and improve autoregistration logic

ci/start_init_test.sh
This commit fix the flaky build due to replica crash, since
autoregistration functionality has been removed.
=> fix(ci): add restart policy for clone replica

app/snapshot.go, ci/start_init_test.sh, package/Dockerfile, scripts/package
This commit copies jivactl binary along with longhorn binary in `/usr/local/bin`.
Output:
```
root@8475c4e498b0:/# jivactl
NAME:
jivactl - A new cli application
USAGE:
jivactl [global options] command [command options] [arguments...]
VERSION:
0.0.0
COMMANDS:
controller		
replica		
sync-agent		
add-replica, add	
ls-replica, ls	
rm-replica, rm	
snapshots, snapshot	
backups, backup	
journal		
GLOBAL OPTIONS:
--url "http://localhost:9501"	
--debug				
--help, -h				show help
--version, -v			print the version
```
=> fix(jiva): copy jivactl binary along with longhorn

replica/backup.go, replica/diff_disk.go, replica/replica.go, replica/replica_test.go, replica/server.go
This commit fixes the following corner cases around delete snapshot command
- return error if it's the latest snapshot
- Optimizing lun map, so that there won't be need of preload
- Drain the data for punch hole from HoleCreatorChan, since file will be
deleted and closed, therefore avoiding case of bad file descriptor
error.
Command to list snapshot: `longhorn snapshot ls`
Command to remove snapshot: `longhorn snapshot rm <snap_name>`
Note: We may miss punching holes for few blocks, if it's already in
progress and delete snapshot request comes up.
Test cases that need to be covered:
1. H->S2->S1->S0:
- Where S0 is autogenerated, S1 is autogenerated but both have data
on different offset. S2 is user created with same data as S0 and
delete S1.
- Where S0 is autogenerated, S1 is …
=> fix(jiva): handle corner cases for snapshot delete

Dockerfile.dapper, ci/start_init_test.sh, controller/client/controller_client.go, controller/control.go, controller/rebuild.go, controller/rest/model.go, controller/rest/replica.go, controller/rest/router.go, controller/rest/volume.go, replica/client/client.go, replica/replica.go, sync/sync.go, types/types.go
This commit adds a new rest api to delete snapshot, following changes
has been done to honor snapshot deletion.
- Move all the snap delete related operations to `/controller/control.go`
- Validate if Replica count = Replication factor
- Don't add replica if snapshot deletion in progress.
- Validate if replica is in RW mode before replace operation
- Rename replicaCount to ReplicationFactor as it was creating confusion
since both are different
=> feat(snap deletion): add rest api to delete snapshot

controller/rest/model.go, controller/rest/volume.go, types/types.go, vendor.conf
This commit adds client status (iscsi initiator) in existing
stats that we expose over rest api from jiva controller on `/v1/stats`
endpoint. It will help us in identifying whether a client is connected
to controller or not.
Depends on openebs/gotgt#22
=> feat(jiva): add client status in target stats

controller/rest/model.go, controller/rest/volume.go, types/types.go, vendor.conf
This commit adds client status (iscsi initiator) in exiting
stats that we expose over rest api from jiva controller on `/v1/stats`
endpoint. It will help us in identifying whether a client is connected
to controller or not.
=> cherry-pick(stats): add client status in target stats (#233)

app/controller.go, app/snapshot.go, controller/control.go, controller/rebuild.go, controller/rest/volume.go, sync/sync.go, types/types.go
Replicas after getting attached to the controller create a
autogenerated snapshots and the maximum allowed autogenerated
snapshots are 512. So this goroutine will be triggered if no
of snapshots are more than 10 and delete the rest snapshots one
by one.
Note: Since snapshot deletion involves merging of data from it's
child to itself, so this may impact the ongoing io's.
=> feat(jiva): add goroutine to delete autogenerated snapshot

.gitlab-ci.yml
- Migrate the k8s 1.11 and 1.12 cluster version and included k8s 1.14 and 1.15 clusters on packet platform.
=> refactor[gitlab]: Run tests in k8s-1.14 & k8s-1.15 clusters on packet platform

.travis.yml, Makefile, package/Dockerfile_build_amd64, package/Dockerfile_build_arm64, scripts/package, scripts/package_debug, scripts/test
Related to:
- openebs/openebs#1295
This PR modify the Makefile to determime the arch and os.
And add Dockerfile_build_arm64 and Dockerfile_build_amd64
to support build for arm64 arch.
Signed-off-by: wangzihao <wangzihao18@huawei.com>
=> Add build for arm

package/Dockerfile_build_arm64, scripts/package, scripts/package_debug
With this change, user can specify a custom
base OS image for arm64 binaries using the ENV
variable BASE_DOCKER_IMAGEARM64.
The default base image will be arm64v8/ubuntu:18.04
Usage:
```
export BASE_DOCKER_IMAGEARM64=arm64v8/ubuntu:16.04; make build
```
=> feat(build): make arm64 base image configurable

replica/extents.go, replica/server.go
This commit fixes the issue where replica was not getting restarted
due to the missing corner case, where tmp file created for verifying
extent mapping support was not deleted due to some errors and we were
not opening the file again (restart case if file already exists) for further operations due to which file ref
was nil and it was giving "invalid argument" error.
fixes: openebs/openebs#2813
=> fix(replica): replica restart failure

package/Dockerfile_tests, scripts/ci, scripts/prepare_test, util/util.go, util/util_test.go
Adds tests for most of the `util` package functions.
- Adds test to most of the `util` package functions.
- This needed a little refactor in the way test are running, since we needed to test `devices`, so I created new script called `scripts/prepare_test` this builds and executes a `container image` based on this file `package/Dockerfile_tests`.
- Inside the container I still use the same `scripts/test` file to run the tests.
- I changed a parameter name to get a more semantic meaning
- I change a method that was not returning the error after failing to stat a file
Fixes https://github.com/openebs/openebs/issues/2776
=> Adds tests to `util` package

.gitlab-ci.yml
- Modified the Branch names for packet platform. For a every K8s release we were creating a new branch in gitlab repo and we have to modify the branch name in gitlab ci yaml. To avoid this branch name has been changed as a generic name.
```
k8s-ultimate means last newer release version [1.16]
k8s-penultimate - second last [1.15]
k8s-antepenultimate - Third last [1.14]
```
=> refactor[gitlab-yaml]: Updated the branch name for packet platform

ci/start_init_test.sh, controller/rebuild.go, replica/client/client.go, replica/replica.go, replica/rest/model.go, replica/rest/replica.go, replica/revision_counter.go, replica/server.go, sync/sync.go
- This commit optimize the rebuild process by comparing the io numbers of the
autogenerated snapshots.
- Now only those snapshots will be synced which have less no of IO's as compared
to healthy replicas.
=> fix(replica): optimize rebuild process

ci/start_init_test.sh, package/Dockerfile_tests
-  This commit adds the regular expression for delete snapshot failure
test case.
-  Comment out the commands to print the process lists and other stack traces of the linux process as it is polluting the debug logs of controller and replica in travis. 
=> refact(ci): fix flaky test cases

ci/start_init_test.sh, controller/control.go, controller/rest/model.go, controller/rest/volume.go
With the earlier approach user needs to fetch the volume id from
`/v1/volumes` endpoint of controller and then generate the resize
url manually.
This commit add action resize to generates the URL for resize operation which
can be used for the REST API calls.
Improve test to verify the same
=> refact(controller): generate url for resize action on volume

app/controller.go, app/replica.go, ci/start_init_test.sh, replica/replica.go, replica/server.go, rpc/client.go, types/types.go, util/util.go
commits adds RPC_READ_TIMEOUT and RPC_WRITE_TIMEOUT env
to configure read and write timeouts values.
=> fix(jiva): make read and write timeouts configurable

app/controller.go, app/replica.go, ci/start_init_test.sh, replica/replica.go, rpc/client.go, types/types.go, util/util.go
commits adds 
- RPC_READ_TIMEOUT and RPC_WRITE_TIMEOUT env to configure read and write timeouts values
- update the default timeouts to 30 secs
cherry-pick https://github.com/openebs/jiva/pull/272
=> fix(jiva): make read and write timeouts configurable (#272)

scripts/push
Fixes an issue with https://github.com/openebs/jiva/pull/275
The images should be pushed to jiva-arm64. 
=> fix(build):arm images to be pushed to jiva-arm64

ci/start_init_test.sh, sync/sync.go
- Comment out the revision count related checks as this is causing
snapshot size mismatch issues where cluster instability is observed due to
network or load on a node.
- comment out some basic tests as travis build time exceeds to 50 minutes.
- Fixes: openebs/openebs#2956
=> revert(replica): comment revision count related checks at replica

replica/replica.go
This commit fixes the issue where snapshot name in meta file was not
updated after the hardlink. So head file name was seen in the replicas
in the meta files of snapshots but due to recent change in #260 we were
updating the metadata again with the latest revision count during reload
operation if revision count less than or equal to 1. So in some of the replicas
it was not updated since reload not occured or revision count was > 1.
This can be understood with the following example.
- Lets consider R1 comes up and creates H0 (revision count = 1)
- R2 comes up creates H1 and renames H0->S0 (metafiles will have H0 as name in
S0 snapshot file) (revision count = 1)
- R2 completes sync from R1 and does reload
- During reload R2 founds revision count =1 thus it updates the metadata with
latest …
=> fix(replica): update snapshot name in metafile

.travis.yml, package/Dockerfile_build_ppc64le, scripts/package, scripts/package_debug, scripts/push
This PR adds builds for jiva on ppc64le. Based on #275. 
- Add auto builds for ppc64le builds.
- Ubuntu:18.04 is a multi arch image, so it can be used directly.
- Dockerfile_build_ppc64le can be used to build on ppc64le env.
- Not running the test on ppc64le.
=> Adding build for ppc64le

app/snapshot.go, controller/replicator.go, controller/rest/model.go, controller/rest/replica.go, controller/rest/volume.go, replica/replica.go, replica/rest/model.go, types/types.go
- This commit improves the logic to only get the usedlogical size from RW
replica and additionally adds following info into stats
* Chain info
* UsedSize of snapshots
* Detailed Snapshot info
- Fix the issue where revision count was showing as zero for the `jivactl
snapshot info` command.
- Move DiskInfo and ReplicaInfo to types.go as it is common across replica and controller
for REST API calls.
=> fix(replica): get usedlogical size info from healthy replica

go.mod, go.sum
This commit update the sparse-tool dependency version which log error info in REST calls.
Fixes: openebs/openebs#2963
=> chore(jiva): update sparse-tools dependency

ci/start_init_test.sh, replica/replica.go, replica/replica_test.go
- This commit fix the issue where replica is not able to recover on
restart if new headfile created with the same name already exists.
- Add a test case to verify the same.
Fixes: https://github.com/openebs/openebs/issues/2907
=> fix(replica): rm headfile if already exists

app/log.go, app/replica.go, controller/client/controller_client.go, controller/rest/model.go, controller/rest/router.go, controller/rest/volume.go, go.mod, go.sum, main.go, replica/client/client.go, replica/replica.go, replica/rest/model.go, replica/rest/replica.go, replica/rest/router.go, replica/server.go, util/util.go
This commit add an option to enable persisting logs to a file. Following
options can be passed to configure log files:
- maxLogFileSize: It is the max size of log that can be hold by a file
in megabites before rotation. Default is 100mb.
If a write would cause the log file to be larger than MaxSize,
the file is closed, renamed to include a timestamp of the current time,
and a new log file is created using the original log file name.
If the length of the write is greater than MaxSize, an error is returned.
- retentionPeriod: It is the max no of days to retain the old files.
Default is 180 days.
- maxBackups: It is the maximum number of old log files to retain.
Default is 5 log files.
- Added command to configure via `jivactl`
For example:
- `./jivactl replica --frontendIP 127.0.0.1 …
=> feat(replica): add option to flush log to file

package/Dockerfile_build_amd64, package/Dockerfile_build_arm64, package/Dockerfile_build_ppc64le, scripts/package, scripts/push
This commit will help customizing docker images via environment variables:
- The following ENV help specify custom docker build args
- DBUILD_SITE_URL ( default: https://openebs.io )
- DBUILD_REPO_URL ( default: https://github.com/openebs/jiva )
- The following ENV allows Travis to specify custom image org
- IMAGE_ORG (default: openebs )
- The following ENV will allow specifying an extra tag suffix
- TAG_SUFFIX ( default: none )
=> refact(build): make the docker images configurable

app/replica.go, changelogs/unreleased/278-utkarshmani1997, changelogs/unreleased/290-utkarshmani1997, changelogs/unreleased/291-utkarshmani1997, changelogs/unreleased/296-payes, changelogs/unreleased/297-utkarshmani1997, changelogs/unreleased/300-payes
This PR fixes the issue of replica remove being triggered multiple times at controller.
When replica comes up, it was sending a Delete command to controller which was just removing the replica from its data structures and not closing the connection threads. And when the connection threads were getting erred out, they were also removing the replica with a specific IP.
As a fix  remove replica has been left to be triggered only by monitor thread at controller.
=> fix(duplica-replica-remove): Avoid calling AutoRmReplica on replica restarts

scripts/push
Using the github tag, docker image tags are
created. As we move the github tags to semver
format, the image tags will end up having a
leading `v` in the tag.
To keep the image tag names consistent with
past releases, the leading `v` will be trimmed
from the travis tag and the rest of the string
will be used for image tag.
Examples:
1.10.0 maps to 1.10.0
v1.10.0 maps to 1.10.0
v1.10.0-custom-RC1 maps to 1.10.0-custom-RC1
=> refactor(build): trim leading v from image tag

app/replica.go, changelogs/unreleased/301-utkarshmani1997, go.mod, go.sum, sync/agent/process.go, types/types.go
Add env SYNC_HTTP_CLIENT_TIMEOUT to make sync client http request timeout configurable.
This env can be passed as container argument.
=> fix(sync): make sync http client timeout configurable

app/replica.go, changelogs/unreleased/301-utkarshmani1997, go.mod, go.sum, sync/agent/process.go, types/types.go
cherry-pick fix(sync): make sync http client timeout configurable (#301)
=> fix(sync): make sync http client timeout configurable (#301)

ci/feature_tests.sh, ci/suite.sh, replica/replica.go
As part of data connection formation between controller and replica, snapshots gets created to allow replicas in WO mode.
And, with few fixes done in 1.7 build, auto snapshot deletion feature has been disabled.
This opened up the issue with the limitation on the number of snapshots.
However, MAX_CHAIN_LENGTH should come for rescue, but, it got a bug with it.
This PR is to fix that bug in honoring value given in MAX_CHAIN_LENGTH env, and, also to increase the default value for max snapshot count.
=> fix(maxChainLen): Increase default maxChainLen to 1024

ci/suite.sh, scripts/package_debug
When building on Travis with IMAGE_REPO env set
to forked repo, the CI scripts were failing
due to a hardcoding of container registry org name as openebs.
This commit helps to re-use the IMAGE ORG
specified in the TRAVIS ENV.
If ENV is not specified, defaults to `openebs`. 
=> refactor(build): fix travis errors on forked repo

ci/suite.sh, scripts/package_debug
When building on Travis with IMAGE_REPO env set to forked repo, the CI scripts were failing due to a hardcoding of container registry org name.
This commit helps to re-use the IMAGE ORG specified in the TRAVIS ENV.
(cherry picked from commit 2d0395bb99fa709bc290f4f889bd943705462d78)
=> refactor(build): fix travis errors on forked repo (#311)

ci/suite.sh, controller/control.go
This commit fixes an issue where controller was waiting to get
clone status after taking c.lock, so any REST request protected
with c.lock was getting blocked till it is released at controller,
hence leading to lock contention in REST requests.
=> fix(replica): lock contention on clone volume

ci/suite.sh, controller/control.go
Below PR has been flagged as not important as clone is not being supported and a bit risky. Lock at controller is being released in between adding replica which might cause race conditions among replicas to get added as leader replica. On error, there will be 2 threads in race to remove the replica, monitoring thread and checkCloneStatus thread.  There can be a case where checkCloneStatus thread removes the replica, replica connects back and after that monitoring thread tries to remove the replica based on errors on old connection.
Reverts openebs/jiva#298
=> Revert "fix(replica): lock contention on clone volume"

replica/replica.go
Head file names were getting repeated after every 10 snapshots. Although this was not causing any  problems as of now but fixing this will help in future implementations where these head file names will be used to sync data. Besides the repetition was not intended.
=> fix(pattern): fix pattern to avoid repetition of head file names after every 10 snapshots

Makefile, controller/control.go, replica/replica.go, sync/sync.go, tests/e2e/chaos.go, tests/e2e/container_start_stop.go, tests/e2e/ios.go, tests/e2e/replica.go, tests/e2e/snapshot.go, tests/functional/add_replica.go, tests/functional/config.go, tests/functional/controller.go, tests/functional/replica.go, tests/functional/test_checkpoint.go, tests/functional/test_functions.go
This PR addresses the following:
1. Remove empty elements from DeleteCandidateChain. This might occur due to the skipping of user created snapshots.
2. Error out user triggered deletion of snapshots if all the replicas are not connected.
3. Avoid deletion of snapshots whose parent is user created and has not been removed.
4. Update e2e tests to detach disk after every IO iteration to avoid caching at client side.
Signed-off-by: payes <payes.anand@mayadata.io>
=> fix(auto-delete-snapshot): Remove empty elements from DeleteCandidateChain

.github/workflows/build.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml, Makefile, Makefile.buildx.mk, ci/suite.sh, package/jiva.Dockerfile, scripts/package, scripts/package_debug, scripts/push
**Why is this PR required? What issue does it fix?:**
This PR adds support for multi-arch builds using github actions.
It also appends the amd64 suffix to the single arch image pushed by travis.
Successfully tested the image locally.
=> chore(build): add support for multiarch build

.travis.yml, Makefile.buildx.mk
**Why is this PR required? What issue does it fix?**:
Enabling more than two arch in the multi-arch builds is resulting in increased build times as well as
intermittent failures in running the builds.
Limiting to two archs - amd64 and arm64 for now.
=> refact(builds): enable amd64 and arm64 multi arch builds

go.mod, go.sum, replica/replica.go, sync/sync.go
This PR along with https://github.com/openebs/sparse-tools/pull/7 fixes the following issue: https://github.com/openebs/jiva/issues/338
On crashing the kernel simultaneously at all the nodes, one of the replica fails to come up and enters into CrashLoopBackOff state with this error:
```failed to read disk data, error while unmarshalling file: volume-snap-1db04a94-0aa0-4404-bbbb-3641392d587f.img.meta```
This issue occured because metadata files are not synced to disk immediately. It is not seen with data files as those are opened with O_DIRECT flag.
As a fix, Metadata files are now being opened with O_SYNC flag.
=> fix(metaFiles): open MetaFiles with O_SYNC flag

go.mod, go.sum, replica/replica.go, sync/sync.go
This PR along with https://github.com/openebs/sparse-tools/pull/7 fixes the following issue: https://github.com/openebs/jiva/issues/338
On crashing the kernel simultaneously at all the nodes, one of the replica fails to come up and enters into CrashLoopBackOff state with this error:
```failed to read disk data, error while unmarshalling file: volume-snap-1db04a94-0aa0-4404-bbbb-3641392d587f.img.meta```
This issue occured because metadata files are not synced to disk immediately. It is not seen with data files as those are opened with O_DIRECT flag.
As a fix, Metadata files are now being opened with O_SYNC flag.
=> cherry-pick(metaFiles-fix): open MetaFiles with O_SYNC flag (#337)

.travis.yml, replica/replica.go, replica/replica_test.go, replica/rest/replica.go, replica/server.go, sync/rebuild/progress.go, sync/sync.go
This PR implements the following:
1. Update go version to 1.14.7
2. Avoid using `Dir` global variable in replica package to aid unit testing.
3.  Use replica IP to create UUID hash
=> refact(UUID): include replica address while creating UUID hash

.github/workflows/build.yml
This Pr fixes the tags for branches other than master. The images pushed via build workflow for branches should have -ci at the end which is missing due to a variable mismatch. The TAG variable is used by the build_binary script so keeping the variable with a different name.
https://github.com/openebs/jiva/blob/d3d9f36eae48befafcbe2396f9fa6bd235e50525/.github/workflows/build.yml#L103
=> fix(actions): fix the image tag for branches

.github/workflows/release.yml
This PR adds the downstream tagging action to release workflow
Ref: https://github.com/openebs/openebs/issues/3352
=> feat(actions): add downstream tagging action
